
name: Node Data Import

on:
  push:
    paths:
      - .github/workflows/cities.yml
  workflow_dispatch:
  schedule:
    - cron: '*/60 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Neo4j import
        uses: johnymontana/flat-graph@v1.2
        with:
          neo4j-user: ${{secrets.NEO4J_USER}}
          neo4j-password: ${{secrets.NEO4J_PASSWORD}}
          neo4j-uri: ${{secrets.NEO4J_URI}}
          filename: cities.json
          cypher-query: >
            UNWIND $value AS cityData    
            MERGE (n:City {id: cityData.id})
            SET n.name = cityData.name, n.lat = toFloat(cityData.lat), n.lng = toFloat(cityData.lng)
