name: Node Data Import

on:
  push:
    paths:
      - .github/workflows/nodes.yml
  workflow_dispatch:
  schedule:
    - cron: '*/60 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Neo4j import
        uses: johnymontana/flat-graph@v1.2
        with:
          neo4j-user: ${{secrets.NEO4J_USER}}
          neo4j-password: ${{secrets.NEO4J_PASSWORD}}
          neo4j-uri: ${{secrets.NEO4J_URI}}
          filename: nodes.json
          cypher-query: >
            UNWIND $value AS nodeData    
            MERGE (n:NetworkNode {id: nodeData.id})
            SET n.name = nodeData.name, n.created = nodeData.created_at
            FOREACH (childId IN nodeData.children |
            MERGE (c:NetworkNode {id: childId})
            MERGE (n)-[:HAS_CHILD]-(c))
